[tool.ruff]
line-length = 120
src = ["."]
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"


[tool.pytest.ini_options]
addopts = "--cov=."

